name: docker

on:
  push:
    tags:
      - v**

jobs:
  docker:
    name: Build and publish docker image
    uses: subsquid/github-workflows/.github/workflows/docker-on-tag.yml@main
    with:
      image_name: subsquid/p2p-worker
      push_latest: true
    secrets:
      DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
